GET http://localhost:3001/api/persons

##########################################

GET http://localhost:3001/info

##########################################

DELETE  http://localhost:3001/67517202c5fd696624569fde

#########################################

PUT http://localhost:3001/api/persons/67517202c5fd696624569fde

Content-Type: application/json

{
    "name":"honda",
    "number":"1234556"
}

########################################

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"rzeadison",
    "number": "09-1234556"

}

# 09-1234556
# 040-22334455

# 1234556
#  1-22334455
#  10-22-334455


##########################################

GET http://localhost:3001/api/persons/

